// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCkrSVCKLk7IEwccgVepkp-DYbC9R35rWU',
    appId: '1:845675232172:web:8f0cd5de7a902b15441809',
    messagingSenderId: '845675232172',
    projectId: 'edreams-19d63',
    authDomain: 'edreams-19d63.firebaseapp.com',
    databaseURL: 'https://edreams-19d63-default-rtdb.firebaseio.com',
    storageBucket: 'edreams-19d63.appspot.com',
    measurementId: 'G-VPNQ7B27DZ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAKF9ffcNxMHOjHnrisBtL2HiuLmK-QRms',
    appId: '1:845675232172:android:13b13f4b3c872e4e441809',
    messagingSenderId: '845675232172',
    projectId: 'edreams-19d63',
    databaseURL: 'https://edreams-19d63-default-rtdb.firebaseio.com',
    storageBucket: 'edreams-19d63.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBa6bOX24lwxExC5sTyrlC4XlgdxK-KWcc',
    appId: '1:845675232172:ios:6904b68ff95dcce3441809',
    messagingSenderId: '845675232172',
    projectId: 'edreams-19d63',
    databaseURL: 'https://edreams-19d63-default-rtdb.firebaseio.com',
    storageBucket: 'edreams-19d63.appspot.com',
    iosClientId: '845675232172-vm9oiddjp61sj3ast8lm2m85ns20vk50.apps.googleusercontent.com',
    iosBundleId: 'Los.Incarreables.edreams',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBa6bOX24lwxExC5sTyrlC4XlgdxK-KWcc',
    appId: '1:845675232172:ios:ab1a83fc1ab33bfe441809',
    messagingSenderId: '845675232172',
    projectId: 'edreams-19d63',
    databaseURL: 'https://edreams-19d63-default-rtdb.firebaseio.com',
    storageBucket: 'edreams-19d63.appspot.com',
    iosClientId: '845675232172-ogvlbqq89ufjv2h3maf71t6ddpl3qevv.apps.googleusercontent.com',
    iosBundleId: 'Los.Incarreables.edreams.RunnerTests',
  );
}
